language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2

install:
  - sudo apt-get install gfortran swig libumfpack5.4.0 liblapack-dev libatlas-base-dev
  - pip install --use-mirrors numpy nose

script:
  - python setup.py clean
  - CFLAGS=-O0 python setup.py install
  - mkdir empty
  - cd empty
  - export PYTHONWARNINGS=default
  - python ../tools/test-installed-scipy.py -vv -m full
